### ISSUE TITLE
Замечания после прочтения

### ISSUE THREAD

**Issue by Tismoney** [Tismoney/research-connectomics#1]
1. Более плавные переходы от начала к концу.;
2. Более подробно описать существующие методы;
3. Изменить заключение;
4. Разобраться со списком литературы.

**Comment by Tismoney** [comment]
+ более подробно пояснить картинки и подчеркнуть результат.

**Comment by unionspace** [comment]
Очепятка: постановка задачи, последний абзац

**Comment by unionspace** [comment]
лишняя запятая: последний абзац постановки задачи

**Comment by unionspace** [comment]
Изменить предложения: 
В связи с этим возникает проблема большой размерности, вследсвтии чего, большого чис-
ла признаков
Во-вторых, данная теория появилась вследствии
того, что исходный графы, а значит и матрицы, были получены путем срванения послой-
ных участков мозга вручную.
Для решения этой проблемы, воспользуемся спектральным разложением (Или что тоже
самое для симметричной матрицы - сингулярное разложение).
После чего, будет использовать вместо матрицы A, матрицу A0

Дальше, убирая k столбцов матрицы V, соответсвующие наименьшим собственным знае-
ниям, и соответсвуенно в матрице Λ сами собственные значения, мы получаем из матрицы
размера (N, N), матрицу размера (N, N-k).

Так для чистых данных, которые никак не нормализуюутся и не перевзвешиваются, зна-
чение по метрике ROC AUC для 100 валидаций выглядит следующим образом

Как можно заметить, используюя только более информативные признаки матрицы (соб-
ственные вектора, умноженные на собственные значения), результат может улучишься
для правильной первоначальной нормировки данных.

**Comment by Tismoney** [comment]
Внесены изменения. Ожидается тотальная проверка.
